/**
 * Regenerates src/app/icon.svg from the Phosphor package.
 *
 * The favicon has to be a static file: Next reads it off disk, and the
 * alternative, an ImageResponse route, cannot render a Phosphor component at
 * all. Satori only accepts intrinsic elements inside <svg>, and Phosphor's
 * SSR base puts a React Fragment (the weight's path group) in there, so
 * `content={<Rabbit />}` fails the build with
 * "Only intrinsic elements are supported inside <svg>".
 *
 * So the mark is rendered from the installed package here and written out,
 * rather than hand-copied. Run via `bun run generate:icon`, which `build`
 * calls first, so the file cannot drift from the installed version.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { Rabbit } from "@phosphor-icons/react/ssr";
import { renderToStaticMarkup } from "react-dom/server";

/** --primary and --primary-foreground resolved to hex; oklch() is unsafe in a favicon. */
const TILE = "#171717";
const MARK = "#FAFAFA";
const RADIUS = 48;
const CANVAS = 256;
/** Same 0.625 icon-to-tile ratio the sidebar uses. */
const SCALE = 0.625;
const OFFSET = Math.round((CANVAS * (1 - SCALE)) / 2);

// Resolved from the cwd rather than import.meta.dir: the latter is Bun-only
// and is not in this package's type surface, so tsc rejects it. The
// `generate:icon` script always runs with apps/web as the cwd.
const OUT = join(process.cwd(), "src", "app", "icon.svg");

const markup = renderToStaticMarkup(
	<Rabbit size={CANVAS} weight="fill" color={MARK} />,
);

// Keep only what is inside Phosphor's <svg>; the wrapper below supplies its
// own viewBox, size and fill.
const inner = markup.slice(
	markup.indexOf(">") + 1,
	markup.lastIndexOf("</svg>"),
);
if (!inner.includes("<path")) {
	throw new Error(
		`No <path> found in the rendered Phosphor markup, so the icon would be blank.\nGot: ${markup.slice(0, 200)}`,
	);
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${CANVAS} ${CANVAS}" width="${CANVAS}" height="${CANVAS}">
  <title>Rinku</title>
  <!-- Generated by scripts/generate-icon.tsx from @phosphor-icons/react. Do not
       edit by hand: run \`bun run generate:icon\`. Mark is Phosphor "Rabbit",
       fill weight. TILE is the primary token, MARK is primary-foreground.
       Both are spelled as hex because an XML comment cannot contain a double
       hyphen, and because oklch() is not safe to rely on in a favicon. -->
  <rect width="${CANVAS}" height="${CANVAS}" rx="${RADIUS}" fill="${TILE}" />
  <g fill="${MARK}" transform="translate(${OFFSET} ${OFFSET}) scale(${SCALE})">${inner}</g>
</svg>
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, svg);
console.log(`wrote ${OUT} (${svg.length} bytes)`);
